#!/bin/bash

# Update the system and install Nginx
sudo apt update
sudo apt install -y nginx

# Set the hostname
hostnamectl set-hostname [380597]-web-02

# Configure custom Nginx response header
sudo bash -c "echo 'add_header X-Served-By $HOSTNAME;' > /etc/nginx/conf.d/custom_header.conf"

# Restart Nginx to apply the changes
sudo systemctl restart nginx

# Display the custom header for verification
echo "Custom header configuration completed. X-Served-By: $HOSTNAME"

