#!/usr/bin/env bash
# This script connects to the server using SSH and the specified private key.

# Define the server IP and private key file
server_ip="54.90.54.242"
private_key="~/.ssh/school"

# Connect to the server using SSH
ssh -i $private_key ubuntu@$server_ip
