#!/usr/bin/env bash
# This script connects to the server using SSH and the specified private key and user

# Connect using SSH with the specified private key and user
ssh -i ~/.ssh/school ubuntu@8.8.8.8

