#!/usr/bin/env bash
# This script creates an RSA key pair.

# Define the key file name
key_name="school"
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -C "Generated key for school" -f "$key_name" -N "$passphrase"

# Print a message to indicate successful key generation
echo "RSA key pair has been created in $key_name and $key_name.pub."

