#!/usr/bin/env bash
# This script generates an RSA key pair with specific requirements

# Name for the private key
private_key_name="school"

# Number of bits for the key
key_bits=4096

# Passphrase for the key
passphrase="betty"

# Generate the key pair
ssh-keygen -t rsa -b "$key_bits" -C "Generated Key" -f "$private_key_name" -N "$passphrase"

# Output success message
echo "RSA key pair generated. Private key: $private_key_name, Public key: $private_key_name.pub"

